/* This file was generated by syncqt. */
#ifndef QT_QTAXSERVER_VERSION_H
#define QT_QTAXSERVER_VERSION_H

#define QTAXSERVER_VERSION_STR "6.11.1"

#define QTAXSERVER_VERSION 0x0601101

#endif // QT_QTAXSERVER_VERSION_H
