QT.core_private.VERSION = 6.11.1
QT.core_private.name = QtCore
QT.core_private.module =
QT.core_private.libs = $$QT_MODULE_LIB_BASE
QT.core_private.includes = $$QT_MODULE_INCLUDE_BASE/QtCore/6.11.1 $$QT_MODULE_INCLUDE_BASE/QtCore/6.11.1/QtCore
QT.core_private.frameworks = 
QT.core_private.depends = core
QT.core_private.uses = 
QT.core_private.module_config = v2 internal_module
QT.core_private.enabled_features = clock-gettime copy_file_range doubleconversion dladdr futimens getauxval getentropy inotify linkat memmem memrchr mimetype-database poll_ppoll posix_sem posix_shm pthread_condattr_setclock pthread_timedjoin renameat2 sysv_sem sysv_shm dup3 accept4 backtrace sha3-fast hijricalendar timezone_locale datetimeparser forkfd_pidfd async-io pcre2 reduce_exports neon arm_crypto arm_sve localtime_r posix_fallocate dbus gui network printsupport sql testlib widgets xml dlopen relocatable glibc_fortify_source stack_protector stack_clash_protection libstdcpp_assertions relro_now_linker largefile enable_new_dtags neon arm_crypto arm_sve
QT.core_private.disabled_features = system-doubleconversion broken-threadlocal-dtors glib icu winsdkicu windows-ioring windows-ioring-skip-builder-param-checks jemalloc journald system-libb2 liburing system-pcre2 poll_pollts poll_poll poll_select pthread_clockjoin qqnx_pps slog2 syslog vxpipedrv cxx20_format cxx23_stacktrace cpp-winrt lttng etw ctf poll-exit-on-error openssl-hash use_bfd_linker use_gold_linker use_lld_linker use_mold_linker android-style-assets gc_binaries developer-build private_tests doc_snippets debug elf_private_full_version no_direct_extern_access x86intrin sse2 sse3 ssse3 sse4_1 sse4_2 avx f16c avx2 avx512f avx512er avx512cd avx512pf avx512dq avx512bw avx512vl avx512ifma avx512vbmi avx512vbmi2 aesni vaes rdrnd rdseed shani lsx lasx mips_dsp mips_dspr2 arm_crc32 localtime_s force-system-libs force-bundled-libs system-zlib stdlib-libcpp dbus-linked libudev openssl intelcet trivial_auto_var_init_pattern libcpp_hardening android_16kb_pages
QMAKE_LIBS_BACKTRACE = 
QMAKE_LIBS_LIBATOMIC = 
QMAKE_LIBS_LIBRT = -lrt
