# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Qt6::Core)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target Qt6::Core
add_library(Qt6::Core SHARED IMPORTED)

set_target_properties(Qt6::Core PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION;QT_COORD_TYPE"
  INTERFACE_COMPILE_DEFINITIONS "QT_CORE_LIB"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/QtCore;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Qt6::Platform;WrapAtomic::WrapAtomic"
  INTERFACE_QT_COORD_TYPE "double"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:${_IMPORT_PREFIX}/./metatypes/qt6core_metatypes.json>"
  QT_DISABLED_PRIVATE_FEATURES "system_doubleconversion;broken_threadlocal_dtors;glib;icu;winsdkicu;windows_ioring;windows_ioring_skip_builder_param_checks;jemalloc;journald;system_libb2;liburing;system_pcre2;poll_pollts;poll_poll;poll_select;pthread_clockjoin;qqnx_pps;slog2;syslog;vxpipedrv;cxx20_format;cxx23_stacktrace;cpp_winrt;lttng;etw;ctf;poll_exit_on_error;openssl_hash;use_bfd_linker;use_gold_linker;use_lld_linker;use_mold_linker;android_style_assets;gc_binaries;developer_build;private_tests;doc_snippets;debug;elf_private_full_version;no_direct_extern_access;x86intrin;sse2;sse3;ssse3;sse4_1;sse4_2;avx;f16c;avx2;avx512f;avx512er;avx512cd;avx512pf;avx512dq;avx512bw;avx512vl;avx512ifma;avx512vbmi;avx512vbmi2;aesni;vaes;rdrnd;rdseed;shani;lsx;lasx;mips_dsp;mips_dspr2;arm_crc32;localtime_s;force_system_libs;force_bundled_libs;system_zlib;stdlib_libcpp;dbus_linked;libudev;openssl;intelcet;trivial_auto_var_init_pattern;libcpp_hardening;android_16kb_pages"
  QT_DISABLED_PUBLIC_FEATURES "glib;jemalloc;cpp_winrt;timezone_tzdb;static;cross_compile;debug_and_release;separate_debug_info;appstore_compliant;simulator_and_device;force_asserts;framework;cxx20;cxx2a;cxx2b;cxx2c;reduce_relocations;wasm_simd128;wasm_exceptions;wasm_jspi;zstd;openssl_linked;opensslv11;opensslv30"
  QT_ENABLED_PRIVATE_FEATURES "clock_gettime;copy_file_range;doubleconversion;dladdr;futimens;getauxval;getentropy;inotify;linkat;memmem;memrchr;mimetype_database;poll_ppoll;posix_sem;posix_shm;pthread_condattr_setclock;pthread_timedjoin;renameat2;sysv_sem;sysv_shm;dup3;accept4;backtrace;sha3_fast;hijricalendar;timezone_locale;datetimeparser;forkfd_pidfd;async_io;pcre2;reduce_exports;neon;arm_crypto;arm_sve;localtime_r;posix_fallocate;dbus;gui;network;printsupport;sql;testlib;widgets;xml;dlopen;relocatable;glibc_fortify_source;stack_protector;stack_clash_protection;libstdcpp_assertions;relro_now_linker;largefile;enable_new_dtags;neon;arm_crypto;arm_sve"
  QT_ENABLED_PUBLIC_FEATURES "clock_monotonic;cxx11_future;cxx17_filesystem;inotify;std_atomic64;mimetype;regularexpression;sharedmemory;shortcut;systemsemaphore;xmlstream;xmlstreamreader;xmlstreamwriter;textdate;datestring;process;processenvironment;temporaryfile;library;settings;filesystemwatcher;filesystemiterator;itemmodel;proxymodel;sortfilterproxymodel;identityproxymodel;transposeproxymodel;concatenatetablesproxymodel;stringlistmodel;translation;easingcurve;animation;gestures;jalalicalendar;islamiccivilcalendar;timezone;commandlineparser;cborstreamreader;cborstreamwriter;permissions;threadsafe_cloexec;version_tagging;shared;pkg_config;rpath;signaling_nan;thread;future;concurrent;dbus;test_gui;test_squish;shared;plugin_manifest;glibc_fortify_source;stack_protector;stack_clash_protection;libstdcpp_assertions;relro_now_linker;shared;rpath;reduce_exports"
  QT_QMAKE_PRIVATE_CONFIG "pcre2;largefile;enable_new_dtags;neon;arm_crypto;arm_sve"
  QT_QMAKE_PUBLIC_CONFIG "shared;plugin_manifest;glibc_fortify_source;stack_protector;stack_clash_protection;libstdcpp_assertions;relro_now_linker"
  QT_QMAKE_PUBLIC_QT_CONFIG "threadsafe_cloexec;shared;rpath;reduce_exports"
  _qt_config_module_name "core"
  _qt_is_internal_library "TRUE"
  _qt_is_internal_target "TRUE"
  _qt_is_public_module "TRUE"
  _qt_module_has_headers "ON"
  _qt_module_has_private_headers "TRUE"
  _qt_module_has_public_headers "TRUE"
  _qt_module_include_name "QtCore"
  _qt_module_interface_name "Core"
  _qt_module_relative_include_dir "../../../include/QtCore"
  _qt_package_name "Qt6Core"
  _qt_package_version "6.11.1"
  _qt_private_module_target_name "CorePrivate"
  _qt_sbom_cydx_bom_serial_number_uuid "02591f20-6d49-5be6-bc9a-e74b4780a967"
  _qt_sbom_cydx_external_bom_link "urn:cdx:02591f20-6d49-5be6-bc9a-e74b4780a967/1#SPDXRef-Package-qtbase-qt-module-Core-dd8fa302f09d"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_MODULE"
  _qt_sbom_package_name "Core"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-module-Core-dd8fa302f09d"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.1-host-linux-aarch64-target-linux-aarch64-8ed123f2-63a2-5a08-aba0-dd8202a20039"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-dd8fa302f09d"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-dd8fa302f09d:SPDXRef-Package-qtbase-qt-module-Core-dd8fa302f09d"
)

if(CMAKE_VERSION VERSION_LESS 3.1.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.1.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/Qt6CoreTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "Qt6::Platform" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
