# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Qt6::Gui)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target Qt6::Gui
add_library(Qt6::Gui SHARED IMPORTED)

set_target_properties(Qt6::Gui PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_COMPILE_DEFINITIONS "QT_GUI_LIB"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/QtGui;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Qt6::Core;WrapOpenGL::WrapOpenGL;\$<TARGET_NAME_IF_EXISTS:WrapVulkanHeaders::WrapVulkanHeaders>"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:${_IMPORT_PREFIX}/./metatypes/qt6gui_metatypes.json>"
  MODULE_PLUGIN_TYPES "accessiblebridge;platforms;platforms_darwin;xcbglintegrations;platformthemes;platforminputcontexts;generic;iconengines;imageformats;egldeviceintegrations;wayland_graphics_integration_client;wayland_decoration_client;wayland_shell_integration"
  QT_DISABLED_PRIVATE_FEATURES "accessibility_atspi_bridge;directfb;directwrite;directwrite3;directwritecolrv1;direct2d;direct2d1_1;vxworksevdev;system_freetype;fontconfig;system_harfbuzz;qqnx_imf;integrityfb;kms;drm_atomic;libinput;integrityhid;libinput_axis_api;libinput_hires_wheel_support;vsp2;mtdev;eglfs_brcm;eglfs_egldevice;eglfs_gbm;eglfs_vsp2;eglfs_mali;eglfs_viv;eglfs_rcar;eglfs_viv_wl;eglfs_openwfd;system_jpeg;system_png;tslib;xcb_sm;system_xcb_xinput;graphicsframecapture;wayland_server;wayland_brcm;wayland_libhybris_egl_server_buffer;wayland_dmabuf_server_buffer"
  QT_DISABLED_PUBLIC_FEATURES "accessibility_atspi_bridge;fontconfig;opengles2;opengles3;opengles31;opengles32;dynamicgl;metal;openvg;system_textmarkdownreader"
  QT_ENABLED_PRIVATE_FEATURES "emojisegmenter;evdev;freetype;harfbuzz;linuxfb;vnc;vkgen;vkkhrdisplay;egl_x11;eglfs;eglfs_x11;gif;ico;jpeg;png;imageio_text_loading;tuiotouch;xcb_glx;xcb_egl_plugin;xcb_xlib;xkbcommon_x11;xlib;multiprocess;raster_64bit;raster_fp;qtgui_threadpool;wayland_client;wayland_egl;wayland_drm_egl_server_buffer;wayland_shm_emulation_server_buffer;wayland_vulkan_server_buffer;wayland_datadevice;wayland_client_primary_selection;wayland_client_fullscreen_shell_v1;wayland_client_wl_shell;wayland_client_xdg_shell;egl_extension_platform_wayland;run_opengl_tests"
  QT_ENABLED_PUBLIC_FEATURES "emojisegmenter;freetype;harfbuzz;opengl;vulkan;egl;ico;sessionmanager;xcb;xcb_glx_plugin;xkbcommon;texthtmlparser;textmarkdownreader;textmarkdownwriter;textodfwriter;cssparser;draganddrop;action;cursor;clipboard;wheelevent;tabletevent;im;highdpiscaling;validator;standarditemmodel;filesystemmodel;imageformatplugin;movie;imageformat_bmp;imageformat_ppm;imageformat_xbm;imageformat_xpm;imageformat_png;imageformat_jpeg;image_heuristic_mask;image_text;picture;colornames;pdf;desktopservices;systemtrayicon;accessibility;whatsthis;undocommand;undostack;undogroup;wayland;waylandscanner"
  QT_QMAKE_PRIVATE_CONFIG ""
  QT_QMAKE_PUBLIC_CONFIG ""
  QT_QMAKE_PUBLIC_QT_CONFIG ""
  _qt_config_module_name "gui"
  _qt_is_internal_library "TRUE"
  _qt_is_internal_target "TRUE"
  _qt_is_public_module "TRUE"
  _qt_module_has_headers "ON"
  _qt_module_has_private_headers "TRUE"
  _qt_module_has_public_headers "TRUE"
  _qt_module_has_qpa_headers "TRUE"
  _qt_module_has_rhi_headers "TRUE"
  _qt_module_include_name "QtGui"
  _qt_module_interface_name "Gui"
  _qt_module_relative_include_dir "../../../include/QtGui"
  _qt_package_name "Qt6Gui"
  _qt_package_version "6.11.1"
  _qt_private_module_target_name "GuiPrivate"
  _qt_sbom_cydx_bom_serial_number_uuid "02591f20-6d49-5be6-bc9a-e74b4780a967"
  _qt_sbom_cydx_external_bom_link "urn:cdx:02591f20-6d49-5be6-bc9a-e74b4780a967/1#SPDXRef-Package-qtbase-qt-module-Gui-dd8fa302f09d"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_MODULE"
  _qt_sbom_package_name "Gui"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-module-Gui-dd8fa302f09d"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.1-host-linux-aarch64-target-linux-aarch64-8ed123f2-63a2-5a08-aba0-dd8202a20039"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-dd8fa302f09d"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-dd8fa302f09d:SPDXRef-Package-qtbase-qt-module-Gui-dd8fa302f09d"
)

if(CMAKE_VERSION VERSION_LESS 3.1.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.1.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/Qt6GuiTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "Qt6::Core" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
