# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Qt6::QSvgPlugin)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target Qt6::QSvgPlugin
add_library(Qt6::QSvgPlugin MODULE IMPORTED)

set_target_properties(Qt6::QSvgPlugin PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  QT_DEFAULT_PLUGIN "1"
  QT_MODULE "Gui"
  QT_PLUGIN_CLASS_NAME "QSvgPlugin"
  QT_PLUGIN_TYPE "imageformats"
  _qt_is_internal_library "TRUE"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_sbom_cydx_bom_serial_number_uuid "a17dc863-1abf-58b1-822b-bde9140275a6"
  _qt_sbom_cydx_external_bom_link "urn:cdx:a17dc863-1abf-58b1-822b-bde9140275a6/1#SPDXRef-Package-qtsvg-qt-plugin-QSvgPlugin-add2a98e8385"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtsvg-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_PLUGIN"
  _qt_sbom_package_name "QSvgPlugin"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtsvg-qt-plugin-QSvgPlugin-add2a98e8385"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtsvg-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtsvg-6.11.1-host-linux-aarch64-target-linux-aarch64-28bce765-8bce-5232-9269-017e57a128f4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtsvg"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtsvg-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtsvg-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtsvg-add2a98e8385"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtsvg-add2a98e8385:SPDXRef-Package-qtsvg-qt-plugin-QSvgPlugin-add2a98e8385"
)

if(CMAKE_VERSION VERSION_LESS 3.1.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.1.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/Qt6QSvgPluginTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
