QT.gui_private.VERSION = 6.11.1
QT.gui_private.name = QtGui
QT.gui_private.module =
QT.gui_private.libs = $$QT_MODULE_LIB_BASE
QT.gui_private.includes = $$QT_MODULE_INCLUDE_BASE/QtGui/6.11.1 $$QT_MODULE_INCLUDE_BASE/QtGui/6.11.1/QtGui
QT.gui_private.frameworks = 
QT.gui_private.depends = core_private gui
QT.gui_private.uses = xkbcommon
QT.gui_private.module_config = v2 internal_module
QT.gui_private.enabled_features = emojisegmenter evdev freetype harfbuzz linuxfb vnc vkgen vkkhrdisplay egl_x11 eglfs eglfs_x11 gif ico jpeg png imageio-text-loading tuiotouch xcb-glx xcb-egl-plugin xcb-xlib xkbcommon-x11 xlib multiprocess raster-64bit raster-fp qtgui-threadpool wayland-client wayland-egl wayland-drm-egl-server-buffer wayland-shm-emulation-server-buffer wayland-vulkan-server-buffer wayland-datadevice wayland-client-primary-selection wayland-client-fullscreen-shell-v1 wayland-client-wl-shell wayland-client-xdg-shell egl-extension-platform-wayland run-opengl-tests
QT.gui_private.disabled_features = accessibility-atspi-bridge directfb directwrite directwrite3 directwritecolrv1 direct2d direct2d1_1 vxworksevdev system-freetype fontconfig system-harfbuzz qqnx_imf integrityfb kms drm_atomic libinput integrityhid libinput-axis-api libinput-hires-wheel-support vsp2 mtdev eglfs_brcm eglfs_egldevice eglfs_gbm eglfs_vsp2 eglfs_mali eglfs_viv eglfs_rcar eglfs_viv_wl eglfs_openwfd system-jpeg system-png tslib xcb-sm system-xcb-xinput graphicsframecapture wayland-server wayland-brcm wayland-libhybris-egl-server-buffer wayland-dmabuf-server-buffer
QMAKE_LIBS_EGL = -lEGL
QMAKE_LIBS_OPENGL = -lGLX -lOpenGL
QMAKE_LIBS_OPENGL_ES2 = -lGLESv2 -lEGL
QMAKE_LIBS_VULKAN = 
QMAKE_LIBS_WAYLAND_SERVER = -lwayland-server
QMAKE_LIBS_WAYLAND_CLIENT = -lwayland-client
QMAKE_LIBS_WAYLAND_CURSOR = -lwayland-cursor
QMAKE_LIBS_WAYLAND_EGL = -lwayland-egl -lwayland-client
QMAKE_LIBS_XLIB = -lX11
QMAKE_LIBS_X11SM = 
QMAKE_LIBS_XCB = -lxcb
QMAKE_LIBS_XCB_CURSOR = -lxcb-cursor -lxcb
QMAKE_LIBS_XCB_ICCCM = -lxcb-icccm -lxcb
QMAKE_LIBS_XCB_UTIL = -lxcb-util -lxcb
QMAKE_LIBS_XCB_IMAGE = -lxcb-image -lxcb-util -lxcb-shm -lxcb
QMAKE_LIBS_XCB_KEYSYMS = -lxcb-keysyms -lxcb
QMAKE_LIBS_XCB_RENDERUTIL = -lxcb-render-util -lxcb-render -lxcb
QMAKE_LIBS_XCB_RANDR = -lxcb-randr -lxcb
QMAKE_LIBS_XCB_SHAPE = -lxcb-shape -lxcb
QMAKE_LIBS_XCB_SHM = -lxcb-shm -lxcb
QMAKE_LIBS_XCB_SYNC = -lxcb-sync -lxcb
QMAKE_LIBS_XCB_XFIXES = -lxcb-xfixes -lxcb-shape -lxcb-render -lxcb
QMAKE_LIBS_XCB_XLIB = -lX11-xcb
QMAKE_LIBS_XCB_XKB = -lxcb-xkb -lxcb
QMAKE_LIBS_XCB_RENDER = -lxcb-render -lxcb
QMAKE_LIBS_XCB_GLX = -lxcb-glx -lxcb
QMAKE_LIBS_XKBCOMMON = -lxkbcommon
QMAKE_LIBS_XKBCOMMON_X11 = -lxkbcommon -lxkbcommon-x11
