# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Qt6::qmlaotstats Qt6::qmlcachegen Qt6::qmldom Qt6::qmllint Qt6::qmltc Qt6::qmltyperegistrar Qt6::qmljsrootgen Qt6::qmlformat Qt6::qmlcontextpropertydump Qt6::qmlimportscanner Qt6::qmlprofiler Qt6::qmltime Qt6::qmlplugindump Qt6::qmltestrunner)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target Qt6::qmlaotstats
add_executable(Qt6::qmlaotstats IMPORTED)

set_target_properties(Qt6::qmlaotstats PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_sbom_cydx_bom_serial_number_uuid "0684868b-0f8b-5f2f-948e-b11c91585598"
  _qt_sbom_cydx_external_bom_link "urn:cdx:0684868b-0f8b-5f2f-948e-b11c91585598/1#SPDXRef-Package-qtdeclarative-qt-tool-qmlaotstats-297826c93590"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmlaotstats"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmlaotstats-297826c93590"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.1-host-linux-aarch64-target-linux-aarch64-28bce765-8bce-5232-9269-017e57a128f4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-297826c93590"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-297826c93590:SPDXRef-Package-qtdeclarative-qt-tool-qmlaotstats-297826c93590"
)

# Create imported target Qt6::qmlcachegen
add_executable(Qt6::qmlcachegen IMPORTED)

set_target_properties(Qt6::qmlcachegen PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_sbom_cydx_bom_serial_number_uuid "0684868b-0f8b-5f2f-948e-b11c91585598"
  _qt_sbom_cydx_external_bom_link "urn:cdx:0684868b-0f8b-5f2f-948e-b11c91585598/1#SPDXRef-Package-qtdeclarative-qt-tool-qmlcachegen-297826c93590"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmlcachegen"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmlcachegen-297826c93590"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.1-host-linux-aarch64-target-linux-aarch64-28bce765-8bce-5232-9269-017e57a128f4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-297826c93590"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-297826c93590:SPDXRef-Package-qtdeclarative-qt-tool-qmlcachegen-297826c93590"
)

# Create imported target Qt6::qmldom
add_executable(Qt6::qmldom IMPORTED)

set_target_properties(Qt6::qmldom PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_sbom_cydx_bom_serial_number_uuid "0684868b-0f8b-5f2f-948e-b11c91585598"
  _qt_sbom_cydx_external_bom_link "urn:cdx:0684868b-0f8b-5f2f-948e-b11c91585598/1#SPDXRef-Package-qtdeclarative-qt-tool-qmldom-297826c93590"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmldom"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmldom-297826c93590"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.1-host-linux-aarch64-target-linux-aarch64-28bce765-8bce-5232-9269-017e57a128f4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-297826c93590"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-297826c93590:SPDXRef-Package-qtdeclarative-qt-tool-qmldom-297826c93590"
)

# Create imported target Qt6::qmllint
add_executable(Qt6::qmllint IMPORTED)

set_target_properties(Qt6::qmllint PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_sbom_cydx_bom_serial_number_uuid "0684868b-0f8b-5f2f-948e-b11c91585598"
  _qt_sbom_cydx_external_bom_link "urn:cdx:0684868b-0f8b-5f2f-948e-b11c91585598/1#SPDXRef-Package-qtdeclarative-qt-tool-qmllint-297826c93590"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmllint"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmllint-297826c93590"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.1-host-linux-aarch64-target-linux-aarch64-28bce765-8bce-5232-9269-017e57a128f4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-297826c93590"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-297826c93590:SPDXRef-Package-qtdeclarative-qt-tool-qmllint-297826c93590"
)

# Create imported target Qt6::qmltc
add_executable(Qt6::qmltc IMPORTED)

set_target_properties(Qt6::qmltc PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_sbom_cydx_bom_serial_number_uuid "0684868b-0f8b-5f2f-948e-b11c91585598"
  _qt_sbom_cydx_external_bom_link "urn:cdx:0684868b-0f8b-5f2f-948e-b11c91585598/1#SPDXRef-Package-qtdeclarative-qt-tool-qmltc-297826c93590"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmltc"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmltc-297826c93590"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.1-host-linux-aarch64-target-linux-aarch64-28bce765-8bce-5232-9269-017e57a128f4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-297826c93590"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-297826c93590:SPDXRef-Package-qtdeclarative-qt-tool-qmltc-297826c93590"
)

# Create imported target Qt6::qmltyperegistrar
add_executable(Qt6::qmltyperegistrar IMPORTED)

set_target_properties(Qt6::qmltyperegistrar PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_sbom_cydx_bom_serial_number_uuid "0684868b-0f8b-5f2f-948e-b11c91585598"
  _qt_sbom_cydx_external_bom_link "urn:cdx:0684868b-0f8b-5f2f-948e-b11c91585598/1#SPDXRef-Package-qtdeclarative-qt-tool-qmltyperegistrar-297826c93590"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmltyperegistrar"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmltyperegistrar-297826c93590"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.1-host-linux-aarch64-target-linux-aarch64-28bce765-8bce-5232-9269-017e57a128f4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-297826c93590"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-297826c93590:SPDXRef-Package-qtdeclarative-qt-tool-qmltyperegistrar-297826c93590"
)

# Create imported target Qt6::qmljsrootgen
add_executable(Qt6::qmljsrootgen IMPORTED)

set_target_properties(Qt6::qmljsrootgen PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_sbom_cydx_bom_serial_number_uuid "0684868b-0f8b-5f2f-948e-b11c91585598"
  _qt_sbom_cydx_external_bom_link "urn:cdx:0684868b-0f8b-5f2f-948e-b11c91585598/1#SPDXRef-Package-qtdeclarative-qt-tool-qmljsrootgen-297826c93590"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmljsrootgen"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmljsrootgen-297826c93590"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.1-host-linux-aarch64-target-linux-aarch64-28bce765-8bce-5232-9269-017e57a128f4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-297826c93590"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-297826c93590:SPDXRef-Package-qtdeclarative-qt-tool-qmljsrootgen-297826c93590"
)

# Create imported target Qt6::qmlformat
add_executable(Qt6::qmlformat IMPORTED)

set_target_properties(Qt6::qmlformat PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_sbom_cydx_bom_serial_number_uuid "0684868b-0f8b-5f2f-948e-b11c91585598"
  _qt_sbom_cydx_external_bom_link "urn:cdx:0684868b-0f8b-5f2f-948e-b11c91585598/1#SPDXRef-Package-qtdeclarative-qt-tool-qmlformat-297826c93590"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmlformat"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmlformat-297826c93590"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.1-host-linux-aarch64-target-linux-aarch64-28bce765-8bce-5232-9269-017e57a128f4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-297826c93590"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-297826c93590:SPDXRef-Package-qtdeclarative-qt-tool-qmlformat-297826c93590"
)

# Create imported target Qt6::qmlcontextpropertydump
add_executable(Qt6::qmlcontextpropertydump IMPORTED)

set_target_properties(Qt6::qmlcontextpropertydump PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_sbom_cydx_bom_serial_number_uuid "0684868b-0f8b-5f2f-948e-b11c91585598"
  _qt_sbom_cydx_external_bom_link "urn:cdx:0684868b-0f8b-5f2f-948e-b11c91585598/1#SPDXRef-Package-qtdeclarative-qt-tool-qmlcontextpropertydump-297826c93590"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmlcontextpropertydump"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmlcontextpropertydump-297826c93590"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.1-host-linux-aarch64-target-linux-aarch64-28bce765-8bce-5232-9269-017e57a128f4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-297826c93590"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-297826c93590:SPDXRef-Package-qtdeclarative-qt-tool-qmlcontextpropertydump-297826c93590"
)

# Create imported target Qt6::qmlimportscanner
add_executable(Qt6::qmlimportscanner IMPORTED)

set_target_properties(Qt6::qmlimportscanner PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_sbom_cydx_bom_serial_number_uuid "0684868b-0f8b-5f2f-948e-b11c91585598"
  _qt_sbom_cydx_external_bom_link "urn:cdx:0684868b-0f8b-5f2f-948e-b11c91585598/1#SPDXRef-Package-qtdeclarative-qt-tool-qmlimportscanner-297826c93590"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmlimportscanner"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmlimportscanner-297826c93590"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.1-host-linux-aarch64-target-linux-aarch64-28bce765-8bce-5232-9269-017e57a128f4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-297826c93590"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-297826c93590:SPDXRef-Package-qtdeclarative-qt-tool-qmlimportscanner-297826c93590"
)

# Create imported target Qt6::qmlprofiler
add_executable(Qt6::qmlprofiler IMPORTED)

set_target_properties(Qt6::qmlprofiler PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_sbom_cydx_bom_serial_number_uuid "0684868b-0f8b-5f2f-948e-b11c91585598"
  _qt_sbom_cydx_external_bom_link "urn:cdx:0684868b-0f8b-5f2f-948e-b11c91585598/1#SPDXRef-Package-qtdeclarative-qt-tool-qmlprofiler-297826c93590"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmlprofiler"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmlprofiler-297826c93590"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.1-host-linux-aarch64-target-linux-aarch64-28bce765-8bce-5232-9269-017e57a128f4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-297826c93590"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-297826c93590:SPDXRef-Package-qtdeclarative-qt-tool-qmlprofiler-297826c93590"
)

# Create imported target Qt6::qmltime
add_executable(Qt6::qmltime IMPORTED)

set_target_properties(Qt6::qmltime PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_qml_backing_library_and_plugin_are_same_target "FALSE"
  _qt_qml_module_class_name "QmlTimePlugin"
  _qt_qml_module_has_plugin "FALSE"
  _qt_qml_module_installed_qmldir_path "qml/QmlTime/qmldir"
  _qt_qml_module_is_backing_target "TRUE"
  _qt_qml_module_target_path "QmlTime"
  _qt_qml_module_uri "QmlTime"
  _qt_qml_module_version "1.0"
  _qt_sbom_cydx_bom_serial_number_uuid "0684868b-0f8b-5f2f-948e-b11c91585598"
  _qt_sbom_cydx_external_bom_link "urn:cdx:0684868b-0f8b-5f2f-948e-b11c91585598/1#SPDXRef-Package-qtdeclarative-qt-tool-qmltime-297826c93590"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmltime"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmltime-297826c93590"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.1-host-linux-aarch64-target-linux-aarch64-28bce765-8bce-5232-9269-017e57a128f4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-297826c93590"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-297826c93590:SPDXRef-Package-qtdeclarative-qt-tool-qmltime-297826c93590"
)

# Create imported target Qt6::qmlplugindump
add_executable(Qt6::qmlplugindump IMPORTED)

set_target_properties(Qt6::qmlplugindump PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_sbom_cydx_bom_serial_number_uuid "0684868b-0f8b-5f2f-948e-b11c91585598"
  _qt_sbom_cydx_external_bom_link "urn:cdx:0684868b-0f8b-5f2f-948e-b11c91585598/1#SPDXRef-Package-qtdeclarative-qt-tool-qmlplugindump-297826c93590"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmlplugindump"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmlplugindump-297826c93590"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.1-host-linux-aarch64-target-linux-aarch64-28bce765-8bce-5232-9269-017e57a128f4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-297826c93590"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-297826c93590:SPDXRef-Package-qtdeclarative-qt-tool-qmlplugindump-297826c93590"
)

# Create imported target Qt6::qmltestrunner
add_executable(Qt6::qmltestrunner IMPORTED)

set_target_properties(Qt6::qmltestrunner PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.1"
  _qt_sbom_cydx_bom_serial_number_uuid "0684868b-0f8b-5f2f-948e-b11c91585598"
  _qt_sbom_cydx_external_bom_link "urn:cdx:0684868b-0f8b-5f2f-948e-b11c91585598/1#SPDXRef-Package-qtdeclarative-qt-tool-qmltestrunner-297826c93590"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.1.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmltestrunner"
  _qt_sbom_package_version "6.11.1"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmltestrunner-297826c93590"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.1-host-linux-aarch64-target-linux-aarch64-28bce765-8bce-5232-9269-017e57a128f4"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.1.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.1.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-297826c93590"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-297826c93590:SPDXRef-Package-qtdeclarative-qt-tool-qmltestrunner-297826c93590"
)

if(CMAKE_VERSION VERSION_LESS 3.1.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.1.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/Qt6QmlToolsTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
