QT.core_private.VERSION = 6.11.1
QT.core_private.name = QtCore
QT.core_private.module =
QT.core_private.libs = $$QT_MODULE_LIB_BASE
QT.core_private.includes = $$QT_MODULE_INCLUDE_BASE/QtCore/6.11.1 $$QT_MODULE_INCLUDE_BASE/QtCore/6.11.1/QtCore
QT.core_private.frameworks = 
QT.core_private.depends = core
QT.core_private.uses = 
QT.core_private.module_config = v2 internal_module
QT.core_private.enabled_features = doubleconversion broken-threadlocal-dtors winsdkicu windows-ioring windows-ioring-skip-builder-param-checks mimetype-database cxx20_format cpp-winrt sha3-fast hijricalendar timezone_locale datetimeparser async-io pcre2 debug neon arm_crypto localtime_s dbus gui network printsupport sql testlib widgets xml relocatable largefile neon arm_crypto
QT.core_private.disabled_features = clock-gettime copy_file_range system-doubleconversion dladdr futimens getauxval getentropy glib icu inotify jemalloc journald system-libb2 linkat liburing memmem memrchr system-pcre2 poll_ppoll poll_pollts poll_poll poll_select posix_sem posix_shm pthread_clockjoin pthread_condattr_setclock pthread_timedjoin qqnx_pps renameat2 slog2 syslog sysv_sem sysv_shm dup3 accept4 vxpipedrv backtrace cxx23_stacktrace lttng etw ctf forkfd_pidfd poll-exit-on-error openssl-hash use_bfd_linker use_gold_linker use_lld_linker use_mold_linker android-style-assets gc_binaries developer-build private_tests doc_snippets elf_private_full_version reduce_exports no_direct_extern_access x86intrin sse2 sse3 ssse3 sse4_1 sse4_2 avx f16c avx2 avx512f avx512er avx512cd avx512pf avx512dq avx512bw avx512vl avx512ifma avx512vbmi avx512vbmi2 aesni vaes rdrnd rdseed shani lsx lasx mips_dsp mips_dspr2 arm_crc32 arm_sve localtime_r posix_fallocate force-system-libs force-bundled-libs system-zlib stdlib-libcpp dbus-linked libudev openssl dlopen intelcet glibc_fortify_source trivial_auto_var_init_pattern stack_protector stack_clash_protection libstdcpp_assertions libcpp_hardening relro_now_linker android_16kb_pages
QMAKE_LIBS_LIBATOMIC = 
